export enum ActionType {
  UPDATE_CELL = 'UPDATE_CELL',
  DELETE_CELL = 'DELETE_CELL',
  INSERT_CELL_AFTER = 'INSERT_CELL_AFTER',
  MOVE_CELL = 'MOVE_CELL',
  BUNDLE_START = 'BUNDLE_START',
  BUNDLE_COMPLETE = 'BUNDLE_COMPLETE',
}
